# Generated by Django 5.2.11 on 2026-02-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Query', 'verbose_name_plural': 'Contact Queries'},
        ),
    ]
